jmartinezmaes/neotype_prelude

- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- src/validated.ts
- test/validated_test.ts
- Simplify the `collect` signatures for `Ior` and `Validated`
- Remove the mapped type aliases for `Either`, `Eval`, and `Maybe`
> Refactor signatures for the `collect` combinators

- test/fn_test.ts
The test for `id` uses fast-check to generate arbitrary properties, and could potentially generate `NaN` as a property. `NaN` is not strictly equal to itself (using `===`), which could cause the test to fail. This applies a filter to the arbitrary property generation to disallow `NaN`.
> Fix flaky arbitrary property generation for the `id` function test

- .gitignore
- package.json
- Add to the list of ignored paths
- Fix a broken path to the `.gitignore` file for the Prettier `--ignore-path` command-line option
> Update the `.gitignore` file

- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
Use the `unknown` type to provide a layer of type safety when accidentally using `yield` inside of generator comprehensions. This moves away from using unary tuples, which eliminates any runtime costs that may have been associated with them.
> Refactor the internal behavior of generator comprehensions

- src/cmb.ts
- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- src/validated.ts
- Revise Markdown link references to be more descriptive
- Remove unnecessary newlines
- Revise the property names in examples for `Eval`
- Fix punctuation in docs for `Ior`
- Revise code fences and docs for `justOrFold` method for `Maybe`
- Revise docs for constructing `Validated`
- Remove unfinished doc sections for "Web requests"
> Polish the spacing, formatting, spelling, and grammar in documentation

- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- src/pair.ts
- src/validated.ts
- Remove duplicate words
- Remove some stale sentences
- Consolidate and reword docs for generator comprehensions
- Reword some docs for comparing and combining types
> Revise documentation for grammar and wording

- src/maybe.ts
- test/maybe_test.ts
Reserve the `orElse` semantics for "alternative" behavior, i.e.:
```
orElse(this: T, that: T): T
```
> For `Maybe`, rename the `justOrElse` method to `justOr`

- package-lock.json
- package.json
- scripts/gen_docsite.tsx
- tsconfig.json
- Upgrade TypeDoc to its latest version
- Generate JSON and output to `site_url/docs.json`
- Remove the `entryPointStrategy` config setting. This didn't seem to be making any difference with how `entryPoints` are configured.
> Update TypeDoc dependency and adjust docs build process

- scripts/gen_docsite.tsx
- src/cmb.ts
- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/fn.ts
- src/ior.ts
- src/maybe.ts
- src/pair.ts
- src/validated.ts
- Add `@remarks` tags to distinguish "summary" sections from "remarks" sections
- Move examples from plain Markdown headings to `@example` tags
- Ensure all examples are isolated and include all relevant imports and types
> Add TSDoc tags to the documentation

- src/either.ts
- src/maybe.ts
- src/validation.ts
- test/either_test.ts
- test/maybe_test.ts
- test/validation_test.ts
Prefer `fold` with `id`, and direct property access, where needed.
> Remove the `*OrFold` methods

- src/either.ts
- src/eval.ts
- src/fn.ts
- src/ior.ts
- src/maybe.ts
- src/validation.ts
- test/either_test.ts
- test/eval_test.ts
- test/fn_test.ts
- test/ior_test.ts
- test/maybe_test.ts
- test/validation_test.ts
This introduces the `lift` combinators for `Either`, `Eval`, `Ior`, `Maybe`, and `Validation`, as well as the `wrapCtor` utility function.
> Introduce the `lift` combinators and `wrapCtor` function

- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- test/either_test.ts
- test/eval_test.ts
- test/ior_test.ts
- test/maybe_test.ts
Prefer `flatMap` with `id` instead.
> Remove the `flat` combinators

- src/cmp.ts
- test/cmp_test.ts
The `Reverse` helper should provide only a modified implementation for `Ord` and avoid prescribing unrelated behavior.
> Remove the semigroup behavior from `Reverse`

- src/cmb.ts
- src/cmp.ts
- src/either.ts
- src/eval.ts
- Reword the docs for working with arbitrary equivalence relations, total orders, and semigroups
- Add a missing word to the docs for the `#[Eq.eq] method`
- Fix an incorrect example of the `clamp` function
- Reword the docs for using `Either` to handle failure
> Correct and reword several parts of the documentation

- src/either.ts
- src/ior.ts
- src/pair.ts
- src/validation.ts
- test/either_test.ts
- test/ior_test.ts
- test/pair_test.ts
- test/validation_test.ts
Prefer only the `lmap` and `map` combinators instead.
> Remove the `bimap` combinators

- .github/workflows/run_tests.yml
- test/cmb_test.ts
- test/cmp_test.ts
- test/common.ts
- test/either_test.ts
- test/eval_test.ts
- test/fn_test.ts
- test/ior_test.ts
- test/maybe_test.ts
- test/pair_test.ts
- test/validation_test.ts
- Use `describe` and `it` blocks to declare expected behavior
- For Chai, Swap the `assert` API with the `expect` API
> Refactor tests to use BDD-style assertions

- src/either.ts
- src/maybe.ts
- test/either_test.ts
- test/maybe_test.ts
- For `Either`, prefer use of `recover` instead.
- For `Maybe`, replace `orElse` with `recover`, which evaluates a function instead of accepting an eager argument.
> For `Either`, and `Maybe`, remove the `orElse` combinators

- .github/workflows/deploy_site.yml
- .github/workflows/run_tests.yml
- Use the Volta action in the setup for the docsite deployment
- Use `npm ci` instead of `npm install`
- Be consistent with capitalization
> Update the CI workflows for building docs and testing

- test/ior_test.ts
- test/validation_test.ts
There is really no need to use arbitrary testing here when there is only one expected result. Use manually created instances instead.
> Trim back arbitraries for testing `Ior` and `Validation`

- src/cmp.ts
- src/ior.ts
- In the docs for the "comparable" corollary for `Ord`, remove the word "either" to not imply an "exclusive or" relationship.
- In the docs for `Ior.gather`, add a missing word.
> Adjust some wording in the documentation

- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- src/validation.ts
- test/either_test.ts
- test/ior_test.ts
- test/maybe_test.ts
- test/validation_test.ts
- Rename `Typ` enumerations to `Kind`
- Rename `typ` discriminator properties to `kind`
Use `Kind` when referring to properties that discriminate union types. This is more descriptive and less obscure than using `typ`, and avoids any ambiguity with the `type` keyword.
> Rename discriminator enumerations and properties

- package.json
- src/either.ts
- src/eval.ts
- src/ior.ts
- src/maybe.ts
- test/either_test.ts
- test/eval_test.ts
- test/ior_test.ts
- test/maybe_test.ts
This PR introduces:
- The `goFn` functions for `Either`, `Eval`, `Ior`, and `Maybe`
- The `goAsyncFn` functions for `Either`, `Ior`, and `Maybe`
These functions provide a higher-order function variant of generator comprehensions that allow the generators to specify zero or more parameters, and return a function that accepts those parameters and forwards them to the generator comprehension.
> Introduce the `goFn` and `goAsyncFn` functions

- src/cmb.ts
- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/fn.ts
- src/internal/mut_stack.ts
- src/ior.ts
- src/maybe.ts
- src/pair.ts
- src/validation.ts
Avoid using generic variable and parameter names like `x` and `y` or `arg` in the source code and documentation. Use clearer, more case-specific names instead.
> Provide better names for variables and parameters

- src/cmb.ts
- src/cmp.ts
- src/either.ts
- src/eval.ts
- src/fn.ts
- src/internal/mut_stack.ts
- src/ior.ts
- src/maybe.ts
- src/pair.ts
- src/validation.ts
- test/cmp_test.ts
- test/either_test.ts
- test/eval_test.ts
- test/fn_test.ts
- test/ior_test.ts
- test/maybe_test.ts
- test/util.ts
- test/validation_test.ts
- Prefer `T` as the default generic parameter for single-parameter types
- Prefer `A` and `B` as the default generic parameters for two-parameter types
- Prefer `TArgs` for describing spread function arguments
- Prefer `TYield` and `TReturn` for describing `yield` and `return` parameters for generator comprehensions
- Prefer more specific names for types with constraints (e.g. using `extends`), except for when the types extend `Eq`, `Ord`, `Semigroup`, or related interfaces
> Choose better names for generic parameters

- src/cmb.ts
- src/cmp.ts
Markdown link references don't seem to work accross TSDoc block scopes (e.g. `@remarks` and `@example`). To work around this, place all links in the same block as their references.
> Fix broken Markdown links in the documentation

- src/either.ts
- Document the `recover` method
- Be consistent when referring to the failures and successes of failed and successful `Either` values, respectively.
Resolves #47
> Revise the module documentation for `Either`

- src/maybe.ts
- test/maybe_test.ts
This better aligns with JavaScript's terminology for nullish values.
> For `Maybe`, rename `fromMissing` to `fromNullish`

- src/_test/utils.ts
- src/either.test.ts
- src/either.ts
- src/eval.test.ts
- src/eval.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/pair.test.ts
- src/validation.test.ts
This PR introduces a new method of writing and interpreting generator comprehensions that better leverages generator functions as first-class constructs. Generator comprehensions may now be written as plain generator or async generator functions. The functions should make use of the `Go` and `GoAsync` return types to indicate that they are a generator comprehension. The `go` and `goAsync` functions will now interpret a generator or an async generator, instead of accepting a generator or async generator function.
This updated syntax has the following advantages:
- Generator comprehensions can be more easily created, reused, and composed.
- Generator comprehensions can now `yield*` other generators directly.
- Return types are now explicit and the type inference of `go` and `goAsync` has …
> Refactor generator comprehensions

- src/either.test.ts
- src/either.ts
- src/eval.test.ts
- src/eval.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/validation.test.ts
- src/validation.ts
This brings them more in-line with existing JavaScript conventions, e.g. `Promise.all`.
> Rename the `collect` combinators to `all`.

- src/either.test.ts
- src/either.ts
- src/eval.test.ts
- src/eval.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/validation.test.ts
- src/validation.ts
This brings them more in-line with the existing `all` combinators.
> Rename the `gather` combinators to `allProps`

- src/_test/utils.test.ts
- src/_test/utils.ts
- src/cmb.test.ts
- src/cmp.test.ts
- src/either.test.ts
- src/eval.test.ts
- src/fn.test.ts
- src/ior.test.ts
- src/maybe.test.ts
- src/pair.test.ts
- src/validation.test.ts
- Choose better names for variables in all unit tests, e.g. prefer "lhs" and "rhs" over "x" and "y".
- Simplify the tests for generator comprehensions.
- Un-nest fast-check properties from fast-check assertions to reduce the amount of indentation.
> Tidy up the unit tests

- src/either.test.ts
- src/either.ts
- src/eval.test.ts
- src/eval.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/validation.test.ts
- src/validation.ts
- Rename the `flatMap` methods to `andThen`
- Rename the `goMap` methods to `andThenGo`
- Rename the `recover` methods to `orElse`
- Introduce the `or` methods
- Reorganize the documentation for chaining and recovery
> Refactor methods for chaining and recovery

- src/_test/utils.ts
- src/either.test.ts
- src/either.ts
- src/eval.test.ts
- src/eval.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/validation.test.ts
- src/validation.ts
For `Either`, `Ior`, `Maybe`, and `Validation`, introduce the `allAsync`, `allPropsAsync`, and `liftAsync` combinators. These allow concurrent collection into their respective data types.
> Introduce asynchronous combinators for collecting into data types.

- .github/workflows/build_and_test.yml
- package.json
- tsconfig.json
Do not test types by default as part of the `npm test` command. Prefer `npm typecheck` instead.
Also, check only types inside of the CI TypeScript test matrix.
> Improve how and when type tests are ran

- package-lock.json
- package.json
- src/cmp.ts
- Replace c8 with v8 as the test coverage provider
- Adjust the implementations of `ieqBy` and `icmpBy` to achieve 100% test coverage
> Upgrade Vitest

- .eslintrc.json
- .prettierrc.json
- package-lock.json
- package.json
- src/builder.test.ts
- src/either.ts
- src/ior.ts
- src/maybe.ts
- src/validation.test.ts
- tsconfig.build.json
- tsconfig.json
Move to tighter linting rules using the `strict-type-checked` and `stylistic-type-checked` recommended rule sets from typescript-eslint.
> Updgrade the libraries and rules for linting

- .github/workflows/build_and_test.yml
- package-lock.json
- package.json
- src/cmb.ts
- src/cmp.ts
- Bump TypeScript, typescript-eslint, and typedoc
- Add TypeScript 5.3 to the CI test matrix
- Remove `@example` tags, use Markdown headings instead (rich text in example titles is not supported by typedoc)
> Support TypeScript 5.3

- src/either.test.ts
- src/either.ts
- src/ior.test.ts
- src/ior.ts
- src/maybe.test.ts
- src/maybe.ts
- src/validation.test.ts
- src/validation.ts
Add constructors that return `void` types. Useful for yielding in generator comprehensions and returning data types from functions that would otherwise return `void` on success.
> Introduce constructors for void values
